### ISSUE TITLE
License

### ISSUE THREAD

**Issue by nfitzen** [Seggan/KingOfTheZiggurat#2]
I noticed that there isn't a license on the repo, which means [you probably can't legally accept contributions, either](https://choosealicense.com/no-permission/). Would you consider adding a license to the repo, such as Expat/[`MIT`], [`GPL-3.0-or-later`], or [CC0 1.0]?

(Obligatory note: not a lawyer, not legal advice.)

[`MIT`]: https://spdx.org/licenses/MIT.html "Expat/MIT License"
[`GPL-3.0-or-later`]: https://spdx.org/licenses/GPL-3.0-or-later.html "GNU General Public License v3.0 or later"
[CC0 1.0]: https://creativecommons.org/publicdomain/zero/1.0/ "Creative Commons Zero 1.0 Universal"

**Comment by Seggan** [comment]
Woops, I usually put licenses on all my projects, somehow I missed this one. Thanks for noticing.
